Fix Windows build error in alljoyn_core/samples/observer/door_consumer.cc
Build error:
alljoyn_core\samples\observer\door_consumer.cc(449) : error C2220: warning treated as error - no 'object' file generated
alljoyn_core\samples\observer\door_consumer.cc(449) : warning C4407: cast between different pointer to member representations, compiler may generate incorrect code
scons: *** [build\win7\x86\debug\obj\alljoyn_core\samples\observer\door_consumer.obj] Error 2
scons: building terminated because of errors.

Change-Id: I2acf52abb918629a915f87e9e0f698fb2fc5b6b8
Signed-off-by: Way Vadhanasin <wayakorn.vadhanasin@microsoft.com>